name: 'Unity Mobile Build Number Bumper'
author: Breakstep Studios
description: 'Github action that retrieves ProjectSettings info for Unity project and outputs it via github actions output.'
branding:
  icon: 'settings'
  color: 'gray-dark'
outputs:
  bundle-version:
    description: "The bundleVersion of the unity project"
    value: ${{ steps.get-project-settings.outputs.bundle-version }}
runs:
  using: "composite"
  steps:
    - name: "Setup Python v3.8"
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: "Get Project Settings"
      id: get-project-settings
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -U unityparser
        python ${{ github.action_path }}/main.py